import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { CustomEditor } from "../components/editor/CustomEditor";
import { ImageUpload } from "../components/upload/ImageUpload";
import { useState } from "react";

export default function Home() {
  const [imageUrl, setImageUrl] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      <main className={styles.main}>
        <div className="space-y-16">


          <div>
            <ImageUpload
              onUpload={(data) => {
                setImageUrl(data.location);
              }}
            />
            {imageUrl ? (
              <>
                <img className="w-1/4" src={imageUrl}></img>
              </>
            ) : (
              <></>
            )}
          </div>

          <div>
            <CustomEditor />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
